---
#
- name: Configure Executor Services
  shell: >
    {{ payara_home }}/bin/asadmin
    --user {{ payara_admin_user }}
    --passwordfile pwdfile
    create-managed-executor-service
    {{ item }}
  args:
    chdir: "{{ payara_home }}/bin"
  with_items: "{{ payara_managed_executor_services }}"
  when: payara_managed_executor_services is defined
  register: create_managed_executor_services
  ignore_errors: true

- debug:
    var: create_managed_executor_services
