---
- name: Configure changepwdfile
  template:
    src: changepwdfile.j2
    dest: "{{ payara_home }}/bin/changepwdfile"

- block:
  - name: Set admin password
    command: >
      {{ payara_home }}/bin/asadmin
      --user {{ payara_admin_user }}
      --passwordfile {{ payara_home }}/bin/changepwdfile
      change-admin-password
    args:
      chdir: "{{ payara_home }}/bin"
    register: command_result
    when: payara_domain_name == "domain1" # only domain1 will have the default password as the password is set when creating other domains
  - debug:
      var: command_result

  - name: Enable secure admin
    command: >
      {{ payara_home }}/bin/asadmin
      --user {{ payara_admin_user }}
      --passwordfile {{ payara_home }}/bin/pwdfile
      enable-secure-admin
    args:
      chdir: "{{ payara_home }}/bin"
    register: command_result
  - debug:
      var: command_result

  always:
  - file:
      path: "{{ payara_home }}/bin/changepwdfile"
      state: absent
    ignore_errors: true

