---
- debug:
    var: payara_deploy_packages

- name: Deploy applications
  command: |
    {{ payara_home }}/bin/asadmin
    --user {{ payara_admin_user }}
    --passwordfile pwdfile
    deploy-remote-archive
    --name {{ item.name }}
    {% if item.contextroot is defined %}
    --contextroot {{ item.contextroot }}
    {% endif %}
    {% if item.target is defined %}
    --target {{ item.target }}
    {% endif %}
    {% if item.virtual is defined and item.virtual %}
    --virtualservers {{ item.virtual }}
    {% endif %}
    {{ item.package }}
  args:
    chdir: "{{ payara_home }}/bin"
  with_items: "{{ payara_deploy_packages }}"
  when: payara_deploy_packages is defined
  register: deploy_applications

- debug:
    var: deploy_applications
