---
# tasks file for payara
- import_tasks: prepare.yml
  become: true

- include_vars: "payara-{{ payara_distribution }}-{{ payara_multilanguage }}-ml.yml"

- import_tasks: install.yml
  become: true

- import_tasks: configure.yml
  become_user: "{{ payara_user }}"
  become: true
  when: payara_distribution != 'micro'

- import_tasks: install-drivers.yml
  when: payara_distribution == 'micro' and payara_jdbc_drivers is defined

- import_tasks: configure-systemd.yml
  when: payara_systemd
  become: true

- import_tasks: start.yml
  when: payara_start and payara_systemd
  become: true
