---
#
- group:
    name: "{{ payara_group }}"
    state: present

- user:
    name: "{{ payara_user }}"
    group: "{{ payara_group }}"
    home: "{{ payara_base }}"
    shell: /bin/bash
    system: true
    createhome: true
    expires: -1
    state: present

- name: Create Ansible tmp dir for payara user
  file:
    path: "{{ payara_base }}/.ansible/tmp"
    state: directory
    owner: "{{ payara_user }}"
    group: "{{ payara_group }}"
    mode: '0755'

- name: Install unarchive packages
  package: name={{ item }} state=latest
  with_items:
    - unzip
    - tar
